config/routes.rb
SecondApp::Application.routes.draw do
  resources :kids

  resources :clans

  get "home/index"
  devise_for :models

  resources :believers
  match '/today'=>"home#today"
  match '/week'=>"home#week"
  match '/anniv'=>"home#anniv"
  match '/annivs'=>"home#annivs"
  match '/allb'=>"home#allb"
   match '/alla'=>"home#alla"

  root :to => 'home#index'

end

app/models/kid.rb
class Kid < ActiveRecord::Base
  attr_accessible :believer_id, :clan_id, :name
end

app/models/kids.rb
class Kids < ActiveRecord::Base
  belongs_to :clan
  attr_accessible :believer_id, :clan_id, :name, :kid_id
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  # GET /kids
  # GET /kids.json
  def index
    @kids = Kid.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kids }
    end
  end

  # GET /kids/1
  # GET /kids/1.json
  def show
    @kid = Kid.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kid }
    end
  end

  # GET /kids/new
  # GET /kids/new.json
  def new
    @kid = Kid.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kid }
    end
  end

  # GET /kids/1/edit
  def edit
    @kid = Kid.find(params[:id])
  end

  # POST /kids
  # POST /kids.json
  def create
    @kid = Kid.new(params[:kid])

    respond_to do |format|
      if @kid.save
        format.html { redirect_to @kid, notice: 'Kid was successfully created.' }
        format.json { render json: @kid, status: :created, location: @kid }
      else
        format.html { render action: "new" }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kids/1
  # PUT /kids/1.json
  def update
    @kid = Kid.find(params[:id])

    respond_to do |format|
      if @kid.update_attributes(params[:kid])
        format.html { redirect_to @kid, notice: 'Kid was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kids/1
  # DELETE /kids/1.json
  def destroy
    @kid = Kid.find(params[:id])
    @kid.destroy

    respond_to do |format|
      format.html { redirect_to kids_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/kids_helper.rb
module KidsHelper
	def believers2
		options = {"Please Select" => ""}
		Believer.all.each do |believer|
			options = options.merge({believer.name => believer.id})
		end
		options
	end
end

app/views/kids/_form.html.erb
<%= form_for(@kid) do |f| %>
  <% if @kid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kid.errors.count, "error") %> prohibited this kid from being saved:</h2>

      <ul>
      <% @kid.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :believer_id %><br />
    <%= f.number_field :believer_id %>
  </div>
  <div class="field">
    <%= f.label :clan_id %><br />
    <%= f.number_field :clan_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kids/edit.html.erb
<h1>Editing kid</h1>

<%= render 'form' %>

<%= link_to 'Show', @kid %> |
<%= link_to 'Back', kids_path %>

app/views/kids/index.html.erb
<h1>Listing kids</h1>

<table>
  <tr>
    <th>Believer</th>
    <th>Clan</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kids.each do |kid| %>
  <tr>
    <td><%= kid.believer_id %></td>
    <td><%= kid.clan_id %></td>
    <td><%= kid.name %></td>
    <td><%= link_to 'Show', kid %></td>
    <td><%= link_to 'Edit', edit_kid_path(kid) %></td>
    <td><%= link_to 'Destroy', kid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Kid', new_kid_path %>

app/views/kids/new.html.erb
<h1>New kid</h1>

<%= render 'form' %>

<%= link_to 'Back', kids_path %>

app/views/kids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Believer:</b>
  <%= @kid.believer_id %>
</p>

<p>
  <b>Clan:</b>
  <%= @kid.clan_id %>
</p>

<p>
  <b>Name:</b>
  <%= @kid.name %>
</p>


<%= link_to 'Edit', edit_kid_path(@kid) %> |
<%= link_to 'Back', kids_path %>