config/routes.rb
SecondApp::Application.routes.draw do
  resources :kids

  resources :clans

  get "home/index"
  devise_for :models

  resources :believers
  match '/today'=>"home#today"
  match '/week'=>"home#week"
  match '/anniv'=>"home#anniv"
  match '/annivs'=>"home#annivs"
  match '/allb'=>"home#allb"
   match '/alla'=>"home#alla"

  root :to => 'home#index'

end

app/models/clan.rb
class Clan < ActiveRecord::Base
  belongs_to :believer
  has_many :kids
  attr_accessor :kids_attributes
  attr_accessible  :name, :father_id, :mother_id, :kid_id, :kids_attributes
  accepts_nested_attributes_for :kids
  
end

app/controllers/clans_controller.rb
class ClansController < ApplicationController
  # GET /clans
  # GET /clans.json
  def index
    @clans = Clan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clans }
    end
  end

  # GET /clans/1
  # GET /clans/1.json
  def show
    @clan = Clan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @clan }
    end
  end

  # GET /clans/new
  # GET /clans/new.json
  def new
    @clan = Clan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clan }
    end
  end

  # GET /clans/1/edit
  def edit
    @clan = Clan.find(params[:id])
  end

  # POST /clans
  # POST /clans.json
  def create
    @clan = Clan.new(params[:clan])

    respond_to do |format|
      if @clan.save
        format.html { redirect_to @clan, notice: 'Clan was successfully created.' }
        format.json { render json: @clan, status: :created, location: @clan }
      else
        format.html { render action: "new" }
        format.json { render json: @clan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clans/1
  # PUT /clans/1.json
  def update
    @clan = Clan.find(params[:id])

    respond_to do |format|
      if @clan.update_attributes(params[:clan])
        format.html { redirect_to @clan, notice: 'Clan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @clan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clans/1
  # DELETE /clans/1.json
  def destroy
    @clan = Clan.find(params[:id])
    @clan.destroy

    respond_to do |format|
      format.html { redirect_to clans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clans_helper.rb
module ClansHelper
	def believers
		 options = {"please Select" => ""}
              Believer.find_all_by_gender("Male").each do |believer|
                      options = options.merge({believer.name => believer.id} )
              end
              options
	end
	def believers1
		 options = {"please Select" => ""}
              Believer.find_all_by_gender("Female").each do |believer|
                      options = options.merge({believer.name => believer.id} )
              end
              options
	end
end

app/views/clans/_form.html.erb
<%= nested_form_for(@clan) do |f| %>
  <% if @clan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clan.errors.count, "error") %> prohibited this clan from being saved:</h2>

      <ul>
      <% @clan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Father %><br />
    <%= f.select :father_id, options_for_select(believers) %>
  </div>
  <div class="field">
    <%= f.label :Mother %><br />
    <%= f.select :mother_id, options_for_select(believers1) %>
  </div>
  <div class="field">
    <%= f.label :Children %><br />
    <%= f.select :kid_id, options_for_select(believers2) %>
  </div>

 Hi
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clans/edit.html.erb
<h1>Editing Family</h1>

<%= render 'form' %>

<%= link_to 'Show', @clan %> |
<%= link_to 'Back', clans_path %>

app/views/clans/index.html.erb
<h1>Listing Families</h1>

<table class="table">
  <tr>
    <th>Father</th>
    <th>Mother</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clans.each do |clan| %>
  <tr>
    <td><%= clan.father_id %></td>
    <td><%= clan.mother_id %></td>
    <td><%= clan.kid_id %></td>
    <td><%= link_to 'Show', clan %></td>
    <td><%= link_to 'Edit', edit_clan_path(clan) %></td>
    <td><%= link_to 'Destroy', clan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Clan', new_clan_path %>

app/views/clans/new.html.erb
<h1>New Family</h1>

<%= render 'form' %>

<%= link_to 'Back', clans_path %>

app/views/clans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Father:</b>
  <%= @clan.father_id %>
</p>
<p>
  <b>Mother:</b>
  <%= @clan.mother_id %>
</p>
<p>
  <b>Name:</b>
  <%= @clan.kid_id%>
</p>


<%= link_to 'Edit', edit_clan_path(@clan) %> |
<%= link_to 'Back', clans_path %>