config/routes.rb
SecondApp::Application.routes.draw do
  resources :kids

  resources :clans

  get "home/index"
  devise_for :models

  resources :believers
  match '/today'=>"home#today"
  match '/week'=>"home#week"
  match '/anniv'=>"home#anniv"
  match '/annivs'=>"home#annivs"
  match '/allb'=>"home#allb"
   match '/alla'=>"home#alla"

  root :to => 'home#index'

end

app/models/believer.rb
class Believer < ActiveRecord::Base
  attr_accessible :dob, :email, :name, :phone, :status, :anniversary, :spouse, :place, :gender, :baptised
  validates_presence_of :name, :phone, :dob,  :status
  validates :phone, numericality: { only_integer: true }
  validates :phone, length: { is: 10 }
  acts_as_birthday :dob, :anniversary 
  before_save :set_anniversary
  has_many :clans

  def set_anniversary
  	
  	if status == "single"
  		self.anniversary = nil
  	end
  end


  def self.get_counts
		counts = {}
		counts[:birthday_count] = Believer.dob_today.count
		counts[:birthdays_week_count] = Believer.find_dobs_for(Time.zone.today.beginning_of_week, Time.zone.today.end_of_week).count    
		counts[:anniv_count] = Believer.anniversary_today.count
		counts[:annivs_week_count] = Believer.find_anniversaries_for(Time.zone.today.beginning_of_week, Time.zone.today.end_of_week).count
		counts
  end
end
def index
     @believers = Believer.sorting_table(params, :name).all
     @believer = Believer.sorting_table(params, :name).all
    end

app/controllers/believers_controller.rb
class BelieversController < ApplicationController
  # GET /believers
  # GET /believers.json
  def index
     @believers = Believer.sorting_table(params, :name).all
     @believer = Believer.sorting_table(params, :name).all
    @believers = Believer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @believers }
    end
  end

  # GET /believers/1
  # GET /believers/1.json
  
  def show
    @believer = Believer.find(params[:id])
    @believer = Believer.sorting_table(params, :name).all
    @believers = Believer.sorting_table(params, :name).all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @believer }
    end
  end

  # GET /believers/new
  # GET /believers/new.json
  def new
    @believer = Believer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @believer }
    end
  end

  # GET /believers/1/edit
  def edit
    @believer = Believer.find(params[:id])
  end

  # POST /believers
  # POST /believers.json
  def create
    @believer = Believer.new(params[:believer])

    respond_to do |format|
      if @believer.save
        format.html { redirect_to @believer, notice: 'Believer was successfully created.' }
        format.json { render json: @believer, status: :created, location: @believer }
      else
        format.html { render action: "new" }
        format.json { render json: @believer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /believers/1
  # PUT /believers/1.json
  def update
    @believer = Believer.find(params[:id])

    respond_to do |format|
      if @believer.update_attributes(params[:believer])
        format.html { redirect_to @believer, notice: 'Believer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @believer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /believers/1
  # DELETE /believers/1.json
  def destroy
    @believer = Believer.find(params[:id])
    @believer.destroy

    respond_to do |format|
      format.html { redirect_to believers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/believers_helper.rb
module BelieversHelper
	def index
     @believers = Believer.sorting_table(params, :name).all
     @believer = Believer.sorting_table(params, :name).all
 end
end

app/views/believers/_form.html.erb
<%= form_for(@believer) do |f| %>
  <% if @believer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@believer.errors.count, "error") %> prohibited this believer from being saved:</h2>

      <ul>
      <% @believer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Gender %><br />
    <%= f.select :gender,options_for_select(["Male","Female"]) %>
  </div>
   <div class="field">
    <%= f.label :Baptised %><br />
    <%= f.select :baptised,options_for_select(["Yes","No"]) %>
  </div>
  <div class="field">
    <%= f.label :Status %><br />
    <%= f.select :status,options_for_select(["single","married"]) %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :Place %><br />
    <%= f.text_field :place %>
  </div>

  <div class="field anniversary_div">
    <%= f.label :anniversary %><br />
    <%= f.date_select :anniversary ,:start_year => 1930%>
  </div>
  <div class="field spouse_div">
    <%= f.label :spouse %><br />
    <%= f.text_field :spouse %>
  </div>
  

  <div class="field">
    <%= f.label :dob %><br />
    <%= f.date_select :dob ,:start_year => 1930%>
  </div>
  
 
   <%= f.submit %>
  </div>
<% end %>
   
 

app/views/believers/edit.html.erb
<h1>Editing believer</h1>

<%= render 'form' %>

<%= link_to 'Show', @believer %> |
<%= link_to 'Back', believers_path %>

app/views/believers/index.html.erb
<h1>Listing believers</h1>

<table class="table">
  <tr>
    <th width="10%">Name</th>
     <th width="10%">Gender</th>
     <th width="10%">Baptised</th>
    <th width="20%">Email</th>
    <th width="12%">Phone</th>
    <th width="10%">Status</th>
    <th width="15%">Dob</th>
    <th width="15%">Anniversary</th>
    <th width="15%">Spouse</th>
    <th width="15%">Place</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%  @believers.each do |believer| %>
  <tr>
    <td><%= believer.name %></td>
    <td><%= believer.gender %></td>
    <td><%= believer.baptised %></td>
    <td><%= believer.email %></td>
    <td><%= believer.phone %></td>
    <td><%= believer.status %></td>
    <td><%= believer.dob.strftime("%a, %d, %b") rescue "Not Found" %></td>
    <td><%= believer.anniversary.strftime("%a, %d, %b") rescue "Not Found" %></td>
    <td><%= believer.spouse rescue "Not Found"%></td>
    <td><%= believer.place %></td>
    <td><%= link_to 'Show', believer %></td>
    <td><%= link_to 'Edit', edit_believer_path(believer) %></td>
    <td><%= link_to 'Destroy', believer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/believers/new.html.erb
<h1>New believer</h1>

<%= render 'form' %>

app/views/believers/show.html.erb
<br><br>

<p id="notice"><%= notice %></p>

<p> Created Successfully </p>
<%= link_to 'Back', believers_path %>