config/routes.rb
SecondApp::Application.routes.draw do
  resources :kids

  resources :clans

  get "home/index"
  devise_for :models

  resources :believers
  match '/today'=>"home#today"
  match '/week'=>"home#week"
  match '/anniv'=>"home#anniv"
  match '/annivs'=>"home#annivs"
  match '/allb'=>"home#allb"
   match '/alla'=>"home#alla"

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Remainder App</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults, "nested_form" %>
  <%= csrf_meta_tags %>
</head>
<body>
<body>
	<div id="wrapper">
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div >
		       <h3 style="font-family:verdana;color:white;font-size:24px;" align="center" >CfC Thirukattupalli</h3>
		      <p style="font-family:verdana;color:white;font-size:24px;" align="right">  
		      	<% if current_model %>
		      		<%= link_to "Sign Out", destroy_model_session_path %>
		      	<% end %>
		      	<!-- <a href="http://localhost:3000/models/sign_out">Sign Out</a> -->
		      </p>
		    </div> 
		   
		    <ul class="nav navbar-right top-nav">
		        
		    </ul>
		    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
		    <% if current_model %>
			    <div class="collapse navbar-collapse navbar-ex1-collapse" >
	             
			        <ul class="nav navbar-nav side-nav"><br><br>
			            <li class="active">
			            	<%= link_to "Home", root_path %>
			            </li>
			            <li>
			            	<%= link_to "Add Records", new_believer_path %>
			            </li>
			            <li>
			            	<%= link_to "Show Records", believers_path %>
			            </li>
			             <li>
			                <%= link_to "Add Family", new_clan_path %>
			            </li>
			            <li>
			                <%= link_to "Show Family", clans_path %>
			            </li>
			        </ul>
			    </div>
		    <% end %>
		    <!-- /.navbar-collapse -->
		</nav>
	
		<div id="page-wrapper">
			<div class="container-fluid"><br>
				<%= yield %>
			</div>
		</div>
	</div>
</body>

</body>
</html>